name: writing_questions_app
description: تطبيق Flutter لإنشاء بنك أسئلة وبناء الاختبارات وتصديرها إلى Word وExcel.
publish_to: none
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'
  flutter: '>=3.22.0'

platforms:
  android:

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  archive: ^3.6.1
  excel: ^4.0.6
  intl: ^0.19.0
  path_provider: ^2.1.4
  provider: ^6.1.2
  share_plus: ^10.0.0
  shared_preferences: ^2.3.2
  uuid: ^4.4.0

dev_dependencies:
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
