import 'dart:developer' as developer;
import 'dart:io';

import 'package:path_provider/path_provider.dart';
import 'package:share_plus/share_plus.dart';

/// A user-facing export failure carrying an already-localized message that
/// can be shown directly in the UI.
class ExportException implements Exception {
  const ExportException(this.message);

  final String message;

  @override
  String toString() => message;
}

/// Centralizes everything the export services share: sanitizing names,
/// writing generated bytes under the application documents directory, and
/// handing the produced file to the system share sheet.
abstract final class ExportFileService {
  /// Characters that are illegal in file names on Android/desktop targets.
  static final RegExp _illegalFileNameChars = RegExp(r'[\\/:*?"<>|]');

  /// Characters that are illegal inside an Excel worksheet name.
  static final RegExp _illegalSheetNameChars = RegExp(r'[\\/*?:\[\]]');

  /// Converts a user-facing label into a safe file-name fragment.
  static String sanitizeFileName(String raw) {
    final cleaned = raw
        .replaceAll(_illegalFileNameChars, '_')
        .replaceAll(RegExp(r'\s+'), '_')
        .trim();
    return cleaned.isEmpty ? 'export' : cleaned;
  }

  /// Converts a label into a valid Excel worksheet name (max 31 characters,
  /// without the characters Excel forbids).
  static String sanitizeSheetName(String raw) {
    var cleaned = raw.replaceAll(_illegalSheetNameChars, ' ').trim();
    if (cleaned.isEmpty) return 'Sheet1';
    if (cleaned.length > 31) cleaned = cleaned.substring(0, 31);
    return cleaned;
  }

  /// Writes [bytes] into [destination] (or the application documents
  /// directory when not provided) under a unique, collision-safe name.
  ///
  /// Passing [destination] explicitly keeps the function unit-testable.
  static Future<File> writeExportFile({
    required String baseName,
    required String extension,
    required List<int> bytes,
    Directory? destination,
  }) async {
    final directory = destination ?? await getApplicationDocumentsDirectory();
    final timestamp = DateTime.now().millisecondsSinceEpoch;
    final file = File(
      '${directory.path}'
      '/${sanitizeFileName(baseName)}_$timestamp.$extension',
    );
    await file.create(recursive: true);
    await file.writeAsBytes(bytes, flush: true);
    return file;
  }

  /// Opens the system share sheet for a previously generated export [file].
  static Future<void> shareExportFile(
    File file, {
    required String mimeType,
    String? subject,
  }) {
    return SharePlus.instance.share(
      ShareParams(
        files: [XFile(file.path, mimeType: mimeType)],
        subject: subject,
        title: subject,
      ),
    );
  }

  /// Logs diagnostics without disturbing the user interface.
  static void logError(String context, Object error, StackTrace stackTrace) {
    developer.log(
      '$context: $error',
      name: 'ExportFileService',
      error: error,
      stackTrace: stackTrace,
    );
  }
}
